### ISSUE TITLE
[Upgrade to 1.6] Print v2 and WMTS overlay layers

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1598]
With print v2 in 1.6, the print of a WMTS overlay layer causes an error.

To reproduce:
* http://nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net/dev/theme/orthophotos
* Print
* PDF

_Also an error with orthophoto as baselayer (via opacity slider)._

Reproduced on cartoriviera too (ping @gnerred)

**Comment by gnerred** [comment]
+1

**Comment by sbrunner** [comment]
Should be fixed with https://github.com/camptocamp/cgxp/pull/1008

**Comment by gnerred** [comment]
I have installed 1.6.4, but this issue is not fixed. When I print, I get an error. To test : 
http://preprodnew.cartoriviera.ch/s/XcDi
Reopen issue ? 
Or is ti something wrong in my config ?

**Comment by sbrunner** [comment]
`baseURL` should be:
`http://preprod.cartoriviera.ch/preprod/tiles/1.0.0/orthos_2014/default/%7BDATE%7D/%7BTileMatrixSet%7D/%7BTileMatrix%7D/%7BTileRow%7D/%7BTileCol%7D.jpeg`
not
`http://preprodnew.cartoriviera.ch/preprod/tiles/1.0.0/orthos_2014/default/{DATE}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.jpeg`

**Comment by sbrunner** [comment]
Will be fixed with https://github.com/geoext/geoext/pull/117
