### ISSUE TITLE
Printing Error with Layertree WMTS combined with WMS

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1784]
There is a printing-problem with layertree-WMTS when combined with (aparently) any wms-vectordata

for an example see URL in this comment:
https://github.com/camptocamp/schwyz_geoportal/issues/189#issuecomment-150225661

**Comment by sbrunner** [comment]
Probably already fixed print issue ... for new version of tomcat

**Comment by kalbermattenm** [comment]
I think that this issue is already resolved, you can test that here: http://sitn.ne.ch/prepub/theme/main (running on 1.6.7rc4)

**Comment by eleu** [comment]
Ok thanks for your answers! We will test when we have upgraded to 1.6.7+

**Comment by eleu** [comment]
Tested again on GMF 1.6.8, the problem is still the same:

For WMTS layers, you cannot have a URL for Query and another for Printing (non-queryable).
