### ISSUE TITLE
[1.6] Print on Demo instance does not work any more

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#1902]
https://geomapfish-demo.camptocamp.net/1.6/

```
javax.net.ssl.SSLException: hostname in certificate didn't match: <127.0.0.1> !=
```

**Comment by rbovard** [comment]
And the checkers...

https://geomapfish-demo.camptocamp.net/1.6/wsgi/check_collector?type=all

**Comment by sbrunner** [comment]
Probably fixed with #877

**Comment by eleu** [comment]
print is still not working on Demo 1.6, but now presumably because of another problem:

```
Failed to do the printing: java.lang.ClassCastException: 
net.sf.jasperreports.functions.standard.DateTimeFunctions cannot be cast to 
net.sf.jasperreports.functions.FunctionSupport (1.0802s)
```

https://geomapfish-demo.camptocamp.net/1.6/
https://geomapfish-demo.camptocamp.net/1.6/wsgi/check_collector?type=all

**Comment by kalbermattenm** [comment]
:smile: :+1: 

Thanks
